# .cpanel.yml

version: 1.0

# Deploy settings
deploy:
  paths:
    - public_html  # Example path where your application will be deployed
  branch: master  # Specify the branch to deploy from

# Environment settings (optional)
env:
  APP_ENV: production
  APP_KEY: dR1B1gzxWcT85U9REbJzBGKZjcLVGb9OwIwjy9KhnwM=
